include "agario-cluster"

agar {

    roles {
        backend = ["backend", "food-mgr", "player-mgr"]
        client = ["player"]
        spectator = ["spectator"]
    }

    core {
        generators = 4
    }

    game {
        map-width = 1000.0
        map-height = 1000.0
        food-spawn-interval = 2000.0
        player-speed = 10.0
        endgame-player-mass = 30000.0
        initial-player-mass = 120.0
        initial-food-mass = 100.0
    }
}