akka {
  actor {
    provider = cluster

    serializers {
        jackson-cbor = "akka.serialization.jackson.JacksonCborSerializer"
    }

    serialization-bindings {
      "it.unibo.agar.distributed.model.serializables.CborSerializable" = jackson-cbor
    }
  }

  remote {
    artery {
      canonical.hostname = "127.0.0.1"
      canonical.port = 0
    }
  }

  cluster {
    seed-nodes = [
      "akka://agario-cluster@127.0.0.1:25251",
      "akka://agario-cluster@127.0.0.1:25252"
    ]
    downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"

    distributed-data {
      gossip-interval = 50ms
      notify-subscribers-interval = 50ms
    }
  }

}
akka.cluster.jmx.multi-mbeans-in-same-jvm = on